name: Build

on:
  push:
    branches: [ master, actions-wip ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [lts/*, 12, 14, 16]

    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm install --global node-gyp
    - name: Removing older ${{ matrix.node-version }} versions
      run: Get-ChildItem lib\native\*\*\$($(node --version).TrimStart("v").Split("\.")[0])* | Remove-Item -Verbose -recurse
    - run: tools/build.bat release $($(node --version).TrimStart("v"))
    - name: Configure git, stage changes
      run: cmd /c 'git config user.name "Github Actions Bot" && git config user.email "41898282+github-actions[bot]@users.noreply.github.com" && git add .'
    - name: Commit
      run: git commit -m "updated to $(node --version)"
    - name: Push
      run: git push
