name: Build

on:
  push:
    branches: [ master, actions-wip ]  

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [lts/*, 12, 14, 16]
      max-parallel: 1

    defaults:
      run:
        shell: powershell
    
    steps:
    - uses: msys2/setup-msys2@v2
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install project dependencies
      run: npm ci
    - name: Install node-gyp
      run: npm install --global node-gyp
    - run: echo "NODE_VERSION_STRING=$(node --version)" | Out-File -FilePath $Env:GITHUB_ENV -Append
    - name: Remove older Node ${{ matrix.node-version }} builds
      run: Get-ChildItem lib\native\*\*\$($(node --version).TrimStart("v").Split("\.")[0])* | Remove-Item -Verbose -recurse
    - name: Build for release
      run: tools/build.bat release $($(node --version).TrimStart("v"))
    - name: List changed files
      run: git status -u --porcelain
    - name: Archive build materials
      run: msys2 -c "tar -cf /tmp/edge-js-build-materials `$(find . -type f -regextype posix-egrep -regex '^\.\/((((src)|(lib\/bootstrap))\/.*)|(((binding\.gyp)|(EdgeJs\.sln))))$')"
    - name: Hash build materials
      run: msys2 -c "shasum -a 1 /tmp/build-materials >> lib/native/last-native-module-build-materials.txt"
    - name: Check if build materials changed
      run: git diff --exit-code lib\native\last-native-module-build-materials.txt && echo "BUILD_MATERIALS_CHANGED=true" | Out-File -FilePath $Env:GITHUB_ENV -Append
    - name: Upload working directory as artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: edge-js-node-${{ env.NODE_VERSION_STRING }}
        path: .
        if-no-files-found: error
    - name: Configure committer, stage changes
      run: cmd /c 'git config user.name "Github Actions Bot" && git config user.email "41898282+github-actions[bot]@users.noreply.github.com" && git add .'
    - name: Commit
      run: git commit -m "update $(node --version) build"
    - name: Ensure changes were only made to lib/ or the saved build materials hash
      run: |
          if (-not ([string]::IsNullOrEmpty((git diff --name-only HEAD HEAD~1 | Select-String "(^lib\/)" -NotMatch)))) {
            throw "Changes were made outside lib/, not pushing!"
          }
    - name: Push
      if: ${{ env.BUILD_MATERIALS_CHANGED }}
      run: git push
