name: Build

on:
  push:
    branches: [ master, actions-wip ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        cache: "npm"
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: dir
    - run: echo ${{ node --version }}
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
        if-no-files-found: error
